// Every school, kindergarten and nursery in Bahrain, so a guardian picks the right one instead
// of typing it and every family writes the same place the same way. A name that is not here can
// still be typed by hand.
//
// Sources, read on 2026-09-23:
//   - schools: data.gov.bh, "Geographical Locations of Public/Private Schools" (official open data)
//   - kindergartens and nurseries: moe.gov.bh educational institutions finder
// Branches that share a name carry their governorate (and block, when two share one).
// Regenerate when the ministry publishes changes.

export type SchoolKind = 'public' | 'private' | 'kindergarten' | 'nursery';

export interface DirectorySchool {
  /** Name as the ministry publishes it. */
  ar: string;
  en: string;
  kind: SchoolKind;
  /** Governorate, lower-case English, as published. */
  gov: string;
}

export const BAHRAIN_SCHOOLS: readonly DirectorySchool[] = [
  {
    ar: 'المدرسة الأمريكية بالبحرين',
    en: 'American School Of Bahrain',
    kind: 'private',
    gov: 'southern',
  },
  { ar: 'المدرسة الباكستانية', en: 'Pakistan School', kind: 'private', gov: 'southern' },
  {
    ar: 'المدرسة الباكستانية الاردية',
    en: 'Pakistan Urdu School',
    kind: 'private',
    gov: 'southern',
  },
  { ar: 'المدرسة البريطانية', en: 'British School', kind: 'private', gov: 'northern' },
  { ar: 'المدرسة البنغلاديشية', en: 'Bangladesh School', kind: 'private', gov: 'capital' },
  { ar: 'المدرسة الشرقية', en: 'Eastern School', kind: 'private', gov: 'capital' },
  { ar: 'المدرسة الفرنسية', en: 'French School', kind: 'private', gov: 'muharraq' },
  { ar: 'المدرسة الفلبينية', en: 'Philippine School', kind: 'private', gov: 'northern' },
  {
    ar: 'المدرسة الكندية في البحرين',
    en: 'Canadian School Bahrain',
    kind: 'private',
    gov: 'muharraq',
  },
  {
    ar: 'المدرسة الهندية (الجنوبية 841)',
    en: 'Indian School (Southern 841)',
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'المدرسة الهندية (الجنوبية 910)',
    en: 'Indian School (Southern 910)',
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'المدرسة الهندية البحرينية',
    en: 'Bahrain Indian School',
    kind: 'private',
    gov: 'northern',
  },
  { ar: 'المدرسة الهندية الجديدة', en: 'The New Indian School', kind: 'private', gov: 'southern' },
  { ar: 'المدرسة اليابانية', en: 'Japanese School', kind: 'private', gov: 'northern' },
  { ar: 'المعهد الديني', en: 'Religious Institute', kind: 'public', gov: 'capital' },
  {
    ar: 'المعهد الديني الابتدائي',
    en: 'The Primary Religious Institute',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'المعهد الديني الجعفري',
    en: 'Jaafari Religious Institute',
    kind: 'public',
    gov: 'capital',
  },
  { ar: 'حضانة أبطال المستقبل', en: "Future Hero's Nursery", kind: 'nursery', gov: 'northern' },
  {
    ar: 'حضانة أجيال منتسوري',
    en: 'Ajyaal Montessori Pre-School',
    kind: 'nursery',
    gov: 'northern',
  },
  { ar: 'حضانة أرض الصغار', en: 'Kids Land Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة أطفال بلا حدود', en: 'Kids Unlimited Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة أطفالي', en: 'Kiddie Pre-school Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة أقواس قزح', en: 'Rainbows Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة الأطفال البهيجة', en: 'Joyful Kids Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة الأم السعيدة', en: 'Happy Mama Nursery', kind: 'nursery', gov: 'muharraq' },
  { ar: 'حضانة الأم إلى الأم', en: 'Mom to Mom Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة الأنامل الصغيرة', en: 'Tiny Finger Tips Nursery', kind: 'nursery', gov: 'southern' },
  {
    ar: 'حضانة البراعم الراقية',
    en: 'Al Baraem Elegant Nursery',
    kind: 'nursery',
    gov: 'muharraq',
  },
  {
    ar: 'حضانة التمهيد البريطاني (الشمالية)',
    en: 'The Bahraini British Pre-school (Northern)',
    kind: 'nursery',
    gov: 'northern',
  },
  { ar: 'حضانة الجفير', en: 'Juffair Nursery', kind: 'nursery', gov: 'capital' },
  { ar: 'حضانة الجواهر الصغيرة', en: 'Little Gems Pre-school', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة الحضانة البريطانية', en: 'The British Nursery', kind: 'nursery', gov: 'southern' },
  { ar: 'حضانة الحضانة الراقية', en: 'Elegant Nursery', kind: 'nursery', gov: 'muharraq' },
  {
    ar: 'حضانة الخطوات الأولى',
    en: "First Steps Children's Nursery",
    kind: 'nursery',
    gov: 'southern',
  },
  { ar: 'حضانة الخليج (سرايا)', en: 'Gulf Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة الدب الصغير', en: 'Little Bear Nursery', kind: 'nursery', gov: 'southern' },
  { ar: 'حضانة الرياحين', en: 'Al Rayaheen Nursery', kind: 'nursery', gov: 'capital' },
  { ar: 'حضانة اللآلئ الصغيرة', en: 'Little Pearls Nursery', kind: 'nursery', gov: 'muharraq' },
  { ar: 'حضانة الياسمين', en: 'Al Yasmeen Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة تطور الأطفال', en: 'Evolution Childcare Nursery', kind: 'nursery', gov: 'capital' },
  { ar: 'حضانة تعلم وامرح', en: 'Learn And Fun Nursery', kind: 'nursery', gov: 'capital' },
  { ar: 'حضانة توينكل', en: 'Twinkle Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة جنة الأطفال', en: 'Janat Al-Atfal Nursery', kind: 'nursery', gov: 'southern' },
  { ar: 'حضانة جيجلز', en: 'Giggles Nursery W.L.L.', kind: 'nursery', gov: 'capital' },
  { ar: 'حضانة دار منزلي الصغير', en: 'My Little House Nursery', kind: 'nursery', gov: 'muharraq' },
  { ar: 'حضانة رعاية الطفل', en: 'Kiddy Care Nursery', kind: 'nursery', gov: 'capital' },
  { ar: 'حضانة ريش', en: 'Reach Nursery', kind: 'nursery', gov: 'capital' },
  { ar: 'حضانة سارة', en: 'Sara Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة سما', en: 'Sama Nursery', kind: 'nursery', gov: 'capital' },
  { ar: 'حضانة شارمنج', en: 'Charming Nursery', kind: 'nursery', gov: 'muharraq' },
  { ar: 'حضانة طريق العباقرة', en: 'Prodigy Lane Preschool', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة عالم العجائب', en: 'Wonder World Nursery', kind: 'nursery', gov: 'muharraq' },
  { ar: 'حضانة عالم سمسم', en: 'Simsim World Nursery', kind: 'nursery', gov: 'muharraq' },
  { ar: 'حضانة عالمي الممتع', en: 'My Fun World Nursery', kind: 'nursery', gov: 'northern' },
  {
    ar: 'حضانة غصون المستقبل المقشع',
    en: 'Ghosoun Future Nursery',
    kind: 'nursery',
    gov: 'northern',
  },
  {
    ar: 'حضانة غصون المستقبل توبلي',
    en: 'Future Ghosoun Tubli Nursery',
    kind: 'nursery',
    gov: 'capital',
  },
  { ar: 'حضانة فيري بيري', en: 'Very Berry Nursery Co W.L.L', kind: 'nursery', gov: 'capital' },
  {
    ar: 'حضانة فيري توبيا (جرداب)',
    en: 'Fairytopia nursery (Jurdab)',
    kind: 'nursery',
    gov: 'southern',
  },
  { ar: 'حضانة فيريتوبيا السيف', en: 'Fairytopia Nursery (Seef)', kind: 'nursery', gov: 'capital' },
  { ar: 'حضانة كدز آيلاند', en: 'Kids Island Nursery', kind: 'nursery', gov: 'capital' },
  { ar: 'حضانة كدز يونيفرس', en: 'Kids Universe Nursery', kind: 'nursery', gov: 'northern' },
  {
    ar: 'حضانة كندر ورلد العدلية',
    en: 'Kinder World Pre School Adliya',
    kind: 'nursery',
    gov: 'capital',
  },
  {
    ar: 'حضانة كندر وورلد - الجنبية',
    en: 'Kinder World Pre school - Janabiyah',
    kind: 'nursery',
    gov: 'capital',
  },
  { ar: 'حضانة كنوز عراد', en: 'Konooz Arad Nursery', kind: 'nursery', gov: 'muharraq' },
  { ar: 'حضانة كيبينا بحرين', en: 'Kipina Bahrain Nursery', kind: 'nursery', gov: 'northern' },
  {
    ar: 'حضانة ليتل سكولرز ذ.م.م',
    en: 'Little Scholars Nursery W.L.L',
    kind: 'nursery',
    gov: 'southern',
  },
  { ar: 'حضانة ليتل وندرز', en: 'Little Wonders Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'حضانة ماجد الزياني', en: 'Majed ALzayani Nursery', kind: 'nursery', gov: 'southern' },
  {
    ar: 'حضانة مادلين (العاصمة)',
    en: "Madeleine's Kindergarten (Capital)",
    kind: 'nursery',
    gov: 'capital',
  },
  { ar: 'حضانة مدينة الأطفال', en: 'Toddlers Town Nursery', kind: 'nursery', gov: 'capital' },
  { ar: 'دار حضانة الطفل السعيد', en: 'Happy Kid Nursery', kind: 'nursery', gov: 'northern' },
  {
    ar: 'دار حضانة الفاتح (العاصمة)',
    en: 'Alfateh Kindergarten (Capital)',
    kind: 'nursery',
    gov: 'capital',
  },
  { ar: 'دار حضانة بيج بن', en: 'Big Ben Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'دار حضانة ركن الطفل', en: 'Kids Corner Nursery', kind: 'nursery', gov: 'northern' },
  { ar: 'دار حضانة سار', en: 'Saar Nursery', kind: 'nursery', gov: 'northern' },
  {
    ar: 'دار حضانة مدرسة الأطفال (إنفنت)',
    en: 'The Infant School (Manma)',
    kind: 'nursery',
    gov: 'capital',
  },
  {
    ar: 'دار حضانة وروضة أ ب ت',
    en: 'ABC Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  {
    ar: 'دار حضانة وروضة البراق',
    en: 'Albiraq Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  {
    ar: 'دار حضانة وروضة الطفل الذكي',
    en: 'Clever Kid Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  {
    ar: 'دار حضانة وروضة القلم',
    en: 'AlQalam Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'دار حضانة وروضة النجوم الصاعدة',
    en: 'Rising stars Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  {
    ar: 'دار حضانة وروضة النجوم الصغيرة',
    en: 'Little starz Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  {
    ar: 'دار حضانة وروضة أم ناصر الفنلندية',
    en: 'Um Nasser Finland Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  {
    ar: 'دار حضانة وروضة حروف',
    en: 'Huroof Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'muharraq',
  },
  {
    ar: 'دار حضانة وروضة خطوة بخطوة',
    en: 'Step By Step Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'دار حضانة وروضة روان', en: 'Rawan Kindergarten', kind: 'kindergarten', gov: 'northern' },
  {
    ar: 'دار حضانة وروضة زهر الجنة',
    en: 'Blossom Paradise Nursery & Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  {
    ar: 'دار حضانة وروضة ستارت سمارت',
    en: 'Start Smart Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'دار حضانة وروضة علاء الدين',
    en: 'Alaa Alddin Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  {
    ar: 'دار حضانة وروضة كانغرو كيدز',
    en: 'Kangaroo Kids International Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'دار حضانة وروضة كي جي كيدز',
    en: 'KG Kids Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  {
    ar: 'دار حضانة وروضة مادلين - سار',
    en: "Madeleine's Nursery and Preschool Saar",
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'دار حضانة وروضة هابي هارتس',
    en: 'Happy Hearts Nursery and Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  { ar: 'دار روضة العهد', en: 'Alahad Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'دارحضانة وروضة المزن', en: 'Almozn Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة آفاق', en: 'Horizons Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة أبجد هوز', en: 'Abjad Hawaz Kindergarten', kind: 'kindergarten', gov: 'capital' },
  {
    ar: 'روضة أجيال المستقبل',
    en: 'Ajyal Almustaqbal Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  { ar: 'روضة أركان', en: 'Arkan Kindergarten', kind: 'kindergarten', gov: 'southern' },
  {
    ar: 'روضة أطفال السلام',
    en: 'Alsalam Kids Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  { ar: 'روضة أطفال أوال', en: 'Awal Kids Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة أطفالنا', en: 'Our Children Kindergarten', kind: 'kindergarten', gov: 'southern' },
  {
    ar: 'روضة الآفاق الحديثة',
    en: 'The New Horizon Preschool',
    kind: 'kindergarten',
    gov: 'capital',
  },
  {
    ar: 'روضة الآمال الصغيرة',
    en: 'Little Hopes Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة الإحسان', en: 'Alehsan Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة الإشراق', en: 'Aleshraq Kindergarten', kind: 'kindergarten', gov: 'capital' },
  {
    ar: 'روضة الإمام الحسن',
    en: 'Alimam Alhassan Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'روضة الإمام محمد بن سعود',
    en: 'Alimam Mohammed bin Saud Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  { ar: 'روضة الأنجال', en: 'Alanjal Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'روضة الانشراح', en: 'Alenshirah Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الأوائل', en: 'Alawael Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة البتول', en: 'Albatool Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة البدور', en: 'Albudoor Kindergarten', kind: 'kindergarten', gov: 'northern' },
  {
    ar: 'روضة البركة (المحرق)',
    en: 'Albaraka Muharraq Kindergarten',
    kind: 'kindergarten',
    gov: 'muharraq',
  },
  {
    ar: 'روضة البركة (مدينة حمد)',
    en: 'Albaraka Hamad Town Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة البشائر', en: 'Albashaer Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة البلابل', en: 'Albalabel Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة البواسم', en: 'Albawasim Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة البيادر', en: 'Albayader Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الجنان', en: 'Aljenan Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الجواهر', en: 'Aljawaher Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة الحكيم', en: 'Alhakeem Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الحنين', en: 'Alhaneen Kindergarten', kind: 'kindergarten', gov: 'southern' },
  {
    ar: 'روضة الخطوات الإيجابية',
    en: 'Positive Steps Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'روضة الخطوة الأولى',
    en: 'First Step Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة الخيرات', en: 'Alkhayrat Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الدانة', en: 'Aldana Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'روضة الدعاء', en: 'Alduaa Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الربيع', en: 'Alrabea Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الرحاب', en: 'Alrehab Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'روضة الرضا', en: 'Alredha Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الرعاية', en: 'Alreaya Kindergarten', kind: 'kindergarten', gov: 'northern' },
  {
    ar: 'روضة الروضة البحرينية البريطانية (الشمالية)',
    en: 'The Bahraini British Pre-school (Northern) 2',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة الريان', en: 'Alrayan Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة الريف', en: 'Alreef Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الزلاق', en: 'Alzallaq Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'روضة الزنج الجديدة', en: 'New Zing Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة الزهراء', en: 'Alzahraa Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة الساية', en: 'Alsayah Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  {
    ar: 'روضة الساية الحد',
    en: 'Alsayah Hidd Kindergarten',
    kind: 'kindergarten',
    gov: 'muharraq',
  },
  { ar: 'روضة السمات', en: 'Alsemat Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة السندباد', en: 'Alsendebad Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الشروق', en: 'Alshorooq Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'روضة الشموس', en: 'Alshomos Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'روضة الصادق', en: 'Alsadiq Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة الصديق', en: 'Alsedeeq Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الصفاء', en: 'Alsafa Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة الضحى', en: 'Alduha Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الضياء', en: 'Aldiaa Kindergarten', kind: 'kindergarten', gov: 'northern' },
  {
    ar: 'روضة الطفل النموذجية',
    en: 'The Model Child Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'روضة الطفولة السعيدة',
    en: 'Happy Childhood Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  { ar: 'روضة الطلائع', en: 'Vanguard Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة العالم الواحد', en: 'One world kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة العطاء', en: 'Alataa Kindergarten', kind: 'kindergarten', gov: 'northern' },
  {
    ar: 'روضة الفاتح النموذجية (العاصمة)',
    en: 'Alfateh Kindergarten (Capital) 2',
    kind: 'kindergarten',
    gov: 'capital',
  },
  { ar: 'روضة الفاروق', en: 'Alfarooq Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة الفجر الجديد', en: 'New Dawn Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'روضة الفرح', en: 'Alfarah Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة الفردوس', en: 'Alfardoos Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'روضة الفرقان', en: 'Alfurqan Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'روضة الفوز', en: 'Alfowz Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  {
    ar: 'روضة القبطان الصغير',
    en: 'Little Captin Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'روضة القدس العربي',
    en: 'Alquds Alarabi Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة القمر', en: 'Alqamar Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة القناديل', en: 'Aghanadeel Kindergarten', kind: 'kindergarten', gov: 'capital' },
  {
    ar: 'روضة المبدع الصغير',
    en: 'Small creator Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  { ar: 'روضة المجد', en: 'Almajd Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة المحبة', en: 'Almahabah Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة المرجان', en: 'Almurjan Kindergarten', kind: 'kindergarten', gov: 'northern' },
  {
    ar: 'روضة المستكشف الصغير',
    en: 'Little Explorer Kindergarten',
    kind: 'kindergarten',
    gov: 'muharraq',
  },
  {
    ar: 'روضة الملاك الصغير',
    en: 'Little Angel Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة المها', en: 'Almaha Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة الناصرية', en: 'Alnaseriyah Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة النبراس', en: 'Alnebras Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة النجاح', en: 'Alnajah Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة النهضة', en: 'Alnahdha Kindergarten', kind: 'kindergarten', gov: 'southern' },
  { ar: 'روضة النورين', en: 'Alnoorain Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة الهداية', en: 'Alhidaya Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  {
    ar: 'روضة الوجوه المبتسمة',
    en: 'Smily Faces Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  { ar: 'روضة الوداد', en: 'Alwedad Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  {
    ar: 'روضة الوسام جونيرز',
    en: 'Alwisam Juniors Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة الوفاء', en: 'Alwafaa Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة الولاء', en: 'Alwalaa Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة اليقين', en: 'Alyageen Kindergarten', kind: 'kindergarten', gov: 'southern' },
  {
    ar: 'روضة أنوار الغدير (1) جدحفص',
    en: 'Anwar Alghadeer Jidhafs Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  {
    ar: 'روضة أنوار الغدير (2) جدعلي',
    en: 'Anwar Alghadeer Jid Ali Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  {
    ar: 'روضة أنوار الغدير (3) عالي',
    en: 'Anwar Alghadeer Aali Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'روضة أنوار الغدير (4) توبلي',
    en: 'Anwar Alghadeer Tubli Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  { ar: 'روضة بدور الغد', en: 'Budoor Alghad Kindergarten', kind: 'kindergarten', gov: 'northern' },
  {
    ar: 'روضة برايت هورايزون',
    en: 'Bright Horizon Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  {
    ar: 'روضة بنك آند بلو',
    en: 'Pink and Blue Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'روضة بيت الأطفال',
    en: "Children's House Kindergarten W.L.L.",
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة تايلوس', en: 'Tylos Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  {
    ar: 'روضة تكوين (الجنوبية)',
    en: 'Takween Kindergarten (Southern)',
    kind: 'kindergarten',
    gov: 'southern',
  },
  {
    ar: 'روضة تكوين القادة (الجنوبية)',
    en: 'Takween Kindergarten (Southern) 2',
    kind: 'kindergarten',
    gov: 'southern',
  },
  { ar: 'روضة جنى', en: 'Jana Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة جود', en: 'Jood Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة جولي لاند', en: 'Jolly Land Kindergarten', kind: 'kindergarten', gov: 'capital' },
  {
    ar: 'روضة حديقة الأطفال',
    en: 'Children Garden Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  {
    ar: 'روضة دانات البديع',
    en: 'Danat Albudaiye Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة درر', en: 'Durar Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  {
    ar: 'روضة رايز اند شاين',
    en: 'Rise and Shine Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  { ar: 'روضة ركن الأطفال', en: 'Kids Corner Kindergarten', kind: 'kindergarten', gov: 'southern' },
  {
    ar: 'روضة زهر الياسمين',
    en: 'Zahr Alyasmeen Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'روضة زهور البنفسج',
    en: 'Zuhoor Albanafsaj Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  { ar: 'روضة زهور الغد', en: 'Zuhoor Alghad Kindergarten', kind: 'kindergarten', gov: 'northern' },
  {
    ar: 'روضة زينة الحياة',
    en: 'Zainat Alhayat Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة سام', en: 'Sam Kindergarten', kind: 'kindergarten', gov: 'southern' },
  {
    ar: 'روضة سدرة العصافير النموذجية',
    en: 'Sedrat Alasafeer Kindergarten',
    kind: 'kindergarten',
    gov: 'muharraq',
  },
  { ar: 'روضة شهد', en: 'Shahad Kindergarten', kind: 'kindergarten', gov: 'northern' },
  {
    ar: 'روضة طريق الخير',
    en: 'Tareeq Alkhair Kindergarten',
    kind: 'kindergarten',
    gov: 'muharraq',
  },
  { ar: 'روضة عالم الأطفال', en: 'Kidz World Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة عباد الشمس', en: 'Sunflower Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة علي بابا', en: 'Ali Baba Kindergarten', kind: 'kindergarten', gov: 'capital' },
  {
    ar: 'روضة قرية الأطفال (الشمالية)',
    en: 'Kids Village Kindergarten (Northern)',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'روضة قرية الصغار (الشمالية)',
    en: 'Kids Village Kindergarten (Northern) 2',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة كل الأطفال', en: 'All Kids Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة كنوز', en: 'Konooz Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  {
    ar: 'روضة لآلئ البحرين',
    en: 'Pearls Bahrain Kindergarten',
    kind: 'kindergarten',
    gov: 'capital',
  },
  { ar: 'روضة لؤلؤة الخليج العربي', en: 'APG Kindergarten', kind: 'kindergarten', gov: 'capital' },
  { ar: 'روضة لامارا', en: 'Lamara Pre-School', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة ليتل سوان', en: 'Little Swan Kindergarten', kind: 'kindergarten', gov: 'northern' },
  { ar: 'روضة لين', en: 'Leen Kindergarten', kind: 'kindergarten', gov: 'capital' },
  {
    ar: 'روضة ماجد الزياني',
    en: 'Majid Alzayani Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'روضة مادلين (العاصمة)',
    en: "Madeleine's Kindergarten (Capital) 2",
    kind: 'kindergarten',
    gov: 'capital',
  },
  {
    ar: 'روضة مايلز أوف سمايلز',
    en: 'Miles of Smiles Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  { ar: 'روضة مدارك', en: 'Madarek Kindergarten', kind: 'kindergarten', gov: 'muharraq' },
  { ar: 'روضة مدينة عيسى', en: 'Isa Town Kindergarten', kind: 'kindergarten', gov: 'southern' },
  {
    ar: 'روضة مصابيح الأمل',
    en: 'Masabeeh Alamal Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'روضة مملكة النحل',
    en: 'Mamlakat Alnahal Kindergarten',
    kind: 'kindergarten',
    gov: 'southern',
  },
  { ar: 'روضة مهد الازهار', en: 'Mahd Alazhar Kindergarten', kind: 'kindergarten', gov: 'capital' },
  {
    ar: 'روضة نادي المحرق',
    en: 'Muharraq Club Kindergarten',
    kind: 'kindergarten',
    gov: 'muharraq',
  },
  {
    ar: 'روضة نجوم الرؤية الحديثة',
    en: 'New Vision Stars Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة نسمة', en: 'Nasmah Kindergarten', kind: 'kindergarten', gov: 'southern' },
  {
    ar: 'روضة نور المعارف',
    en: 'Noor Almaaref Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  { ar: 'روضة هيا نبدأ', en: 'Lets Start Kindergarten', kind: 'kindergarten', gov: 'southern' },
  {
    ar: 'روضة واحة الأطفال',
    en: 'Children Oasis Kindergarten',
    kind: 'kindergarten',
    gov: 'northern',
  },
  {
    ar: 'مدارس الفلاح الخاصة للبنات',
    en: 'Al Falah Private Schools - Girls',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدارس الفلاح الخاصة للبنين (الشمالية)',
    en: 'Al Falah Private Schools - Boys (Northern)',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدارس الفلاح الخاصة للبنين (المحرق)',
    en: 'Al Falah Private Schools - Boys (Muharraq)',
    kind: 'private',
    gov: 'muharraq',
  },
  { ar: 'مدرسة آسيا', en: 'The Asian School', kind: 'private', gov: 'capital' },
  {
    ar: 'مدرسة آمنة بنت وهب الابتدائية للبنات',
    en: "A'Amena Bint Wahab Primary Girls School",
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة إبن النفيس الابتدائية للبنين',
    en: 'Ibn Al Nafis Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة إبن الهيثم الأسلامية (الشمالية)',
    en: 'Ibn Alhaytham Islamic School (Northern)',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة إبن الهيثم الأسلامية (العاصمة)',
    en: 'Ibn Alhaytham Islamic School (Capital)',
    kind: 'private',
    gov: 'capital',
  },
  {
    ar: 'مدرسة إبن خلدون الوطنية',
    en: 'Ibn Khuldoon National School',
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'مدرسة إبن رشد الاعدادية للبنين',
    en: 'Ibn Roshd Intermediate Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة إبن سينا الابتدائية للبنين',
    en: 'Ibn Sina Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة إبن طفيل الابتدائية للبنين',
    en: 'Ibn Tufail Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  { ar: 'مدرسة إبنيزر الخاصة', en: 'Ebenezer Private School', kind: 'private', gov: 'northern' },
  {
    ar: 'مدرسة أبو العلاء المعري الابتدائية للبنين',
    en: 'Abu Al Aala Al Maari Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة أبو بكر الصديق الابتدائية للبنين',
    en: 'Abu Baker Al Siddiq Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة أبو صيبع الابتدائية للبنين',
    en: 'Abu Saibea Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة أبو عبيدة بن الجراح الابتدائية للبنين',
    en: 'Abu Aubaydah Al Jarrah Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة أبو فراس الحمداني الابتدائية للبنين',
    en: 'Abu Feras Alhamadany Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة أحمد العمران الثانوية للبنين',
    en: 'Ahmed Al Omran Secondary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة أحمد الفاتح الابتدائية الاعدادية للبنين',
    en: 'Ahmed Al Fateh Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة أسامة بن زيد الابتدائية للبنين',
    en: 'Osamah Bin Zaid Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة اسماء ذات النطاقين الابتدائية للبنات',
    en: 'Asmaa That Alnetaqain Primary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الإبداع الخاصة (الشمالية)',
    en: 'Creativity Private School (Northern)',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الابداع الخاصة (العاصمة)',
    en: 'Creativity Private School (Capital)',
    kind: 'private',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الإبداع العلمي الدولية',
    en: 'International School Of Creative Science',
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الاستقلال الثانوية للبنات',
    en: 'Al Estiqlal Secondary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  { ar: 'مدرسة الاطفال', en: 'The Infant School', kind: 'private', gov: 'capital' },
  {
    ar: 'مدرسة الاطفال والمواهب الدولية (الجنوبية)',
    en: 'Talents International & The Infant School (Southern)',
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الاطفال والمواهب الدولية (العاصمة)',
    en: 'Talents International & The Infant School (Capital)',
    kind: 'private',
    gov: 'capital',
  },
  { ar: 'مدرسة الاّفاق الحديثة', en: 'The New Horizon School', kind: 'private', gov: 'capital' },
  {
    ar: 'مدرسة الألفية الجديدة (الشمالية)',
    en: 'New Millennium School - Dps (Northern)',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الألفية الجديدة (العاصمة)',
    en: 'New Millennium School - Dps (Capital)',
    kind: 'private',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الإمام الطبري الابتدائية للبنين',
    en: 'Al Emam Altabari Primary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الإمام الغزالي الاعدادية للبنين',
    en: 'Al Emam Al Ghazali Intermediate Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الإمام علي بن أبي طالب الابتدائية الاعدادية للبنين',
    en: 'Al Emam Ali Bin Abi Taleb Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الإمام مالك بن أنس الابتدائية للبنين',
    en: 'Al Emam Malek Bin Anas Primary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الاندلس الابتدائية للبنات',
    en: 'Al Andalus Primary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  { ar: 'مدرسة الإيمان للبنات', en: 'Al Iman Girls School', kind: 'private', gov: 'southern' },
  { ar: 'مدرسة الإيمان للبنين', en: 'Al Iman Boys School', kind: 'private', gov: 'southern' },
  { ar: 'مدرسة البحرين', en: 'Bahrain School', kind: 'private', gov: 'capital' },
  {
    ar: 'مدرسة البحرين المهنية الثانوية للبنين',
    en: 'Bahrain Professional Secondary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة البديع الابتدائية الاعدادية للبنات',
    en: 'Al Budaiya Primary & Intermediate Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة البديع الابتدائية للبنين',
    en: 'Al Budaiya Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة البسيتين الابتدائية للبنات',
    en: 'Busaiteen Primary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة البسيتين الابتدائية للبنين',
    en: 'Al Busaiteen Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة البسيتين الإعدادية للبنات',
    en: 'Al Busaiteen Intermediate Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة البسيتين الاعدادية للبنين',
    en: 'Al Busaiteen Intermediate Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة البلاد القديم الابتدائية للبنات',
    en: 'Albilad Alqadim Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة التضامن الثانوية للبنات',
    en: 'Altadhamun Secondary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة التعاون الثانوية للبنين',
    en: 'Altaawon Secondary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  { ar: 'مدرسة التعليم العصري', en: 'Modern Education School', kind: 'private', gov: 'northern' },
  {
    ar: 'مدرسة الجابرية الصناعية الثانوية للبنين',
    en: 'Al Jaberiya Secondary Technical Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الجزيرة الابتدائية للبنين',
    en: 'Al Jazeerah Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الجسرة الابتدائية للبنين',
    en: 'Al Jasrah Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الحد الابتدائية الاعدادية للبنين',
    en: 'Hidd Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الحد الابتدائية للبنبن',
    en: 'Hidd Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الحد الاعدادية للبنات',
    en: 'Hidd Intermediate Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الحد الثانوية للبنات',
    en: 'Hidd Secondary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الحكمة الدولية النموذجية',
    en: 'Al Hekma International Model School',
    kind: 'private',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الحنينية الابتدائية للبنات',
    en: 'Al Hunayniyah Primary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الحورة الثانوية للبنات',
    en: 'Al Hoora Secondary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الخليج العربي الابتدائية الاعدادية للبنات',
    en: 'Al Khaleej Al Arabi Primary & Intermediate Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الخليل بن احمد الاعدادية للبنين',
    en: 'Al Khalil Bin Ahmed Intermediate Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الخميس الابتدائية للبنين',
    en: 'Al Khamis Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الخنساء الابتدائية للبنات',
    en: 'Al Khansa Primary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الخوارزمي الابتدائية للبنين',
    en: 'Al Khawarezmy Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الدراز الابتدائية للبنات',
    en: 'Al Diraz Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الدراز الاعدادية للبنات',
    en: 'Al Diraz Intermediate Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الدراز الاعدادية للبنين',
    en: 'Al Diraz Intermediate Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الدير الابتدائية الاعدادية للبنات',
    en: 'Al Dair Primary & Intermediate Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الدير الابتدائية للبنين',
    en: 'Al Dair Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الديه الابتدائية الاعدادية للبنات',
    en: 'Al Daih Primary & Intermediate Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الرازي الابتدائية للبنين',
    en: 'Al Razi Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  { ar: 'مدرسة الرؤية الحديثة', en: 'New Vision School', kind: 'private', gov: 'northern' },
  { ar: 'مدرسة الرجاء', en: 'Al Raja School', kind: 'private', gov: 'capital' },
  {
    ar: 'مدرسة الرشيد الابتدائية للبنين',
    en: 'Alrasheed Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الرفاع الاعدادية للبنين',
    en: 'Riffa Intermediate Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الرفاع الشرقي الابتدائية للبنات',
    en: 'East Riffa Primary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الرفاع الشرقي الابتدائية للبنين',
    en: 'East Riffa Primary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الرفاع الشرقي الاعدادية للبنات',
    en: 'East Riffa Intermediate Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الرفاع الشرقي الثانوية للبنين',
    en: 'East Riffa Secondary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الرفاع الغربي الابتدائية للبنات',
    en: 'West Riffa Primary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الرفاع الغربي الابتدائية للبنين',
    en: 'West Riffa Primary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الرفاع الغربي الاعدادية للبنات',
    en: 'West Riffa Intermediate Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الرفاع الغربي الثانوية للبنات',
    en: 'West Riffa Secondary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الرفاع فيوز الدولية',
    en: 'Riffa Views International School',
    kind: 'private',
    gov: 'southern',
  },
  { ar: 'مدرسة الروابي', en: 'Al Rawabi School', kind: 'private', gov: 'northern' },
  {
    ar: 'مدرسة الروضة الابتدائية للبنات',
    en: 'Al Rawdah Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الروضة الابتدائية للبنين',
    en: 'Al Rawdah Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الزلاق الابتدائية الاعدادية للبنات',
    en: 'Al Zallaq Primary & Intermediate Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الزلاق الابتدائية الاعدادية للبنين',
    en: 'Al Zallaq Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'southern',
  },
  { ar: 'مدرسة السلام', en: 'Al Salam School', kind: 'private', gov: 'northern' },
  {
    ar: 'مدرسة السلام الابتدائية للبنات',
    en: 'Al Salam Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة السلمانية الابتدائية للبنات',
    en: 'Alsalmaniya Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة السلمانية الاعدادية للبنين',
    en: 'Alsalmaniya Intermediate Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة السنابس الابتدائية للبنات',
    en: 'Alsanabis Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة السنابس الابتدائية للبنين',
    en: 'Alsanabis Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة السنابس الاعدادية للبنات',
    en: 'Alsanabis Intermediate Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة السهلة الابتدائية الاعدادية للبنين',
    en: 'Al Sehla Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة السهلة الابتدائية للبنات',
    en: 'Al Sehla Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  { ar: 'مدرسة الشرق الاوسط', en: 'Middle East Schools', kind: 'private', gov: 'capital' },
  {
    ar: 'مدرسة الشروق الثانوية للبنات',
    en: 'Al Shorooq Secondary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الشويفات الدولية',
    en: 'The International School Of Choueifat',
    kind: 'private',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الشيخ عبدالعزيز بن محمد الثانوية للبنين',
    en: 'Shaikh Abdulaziz Bin Muhammad Secondary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الشيخ عبدالله بن عيسى آل خليفة الصناعية الثانوية للبنين',
    en: 'Shaikh Abdullah Bin Isa Aal Khalifa Secondary Technical Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الشيخ عيسى بن علي آل خليفة الثانوية للبنين',
    en: 'Shaikh Isa Bin Ali Aal Khalifa Secondary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الشيخ محمد بن عيسى الابتدائية للبنين',
    en: 'Shaikh Muhammad Bin Isa Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الشيخة حصة للبنات',
    en: 'Al Shaikha Hessa Girls School',
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الصفا الابتدائية للبنات',
    en: 'Al Safa Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الضياء الابتدائية للبنين',
    en: 'Al Dhiyaa Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة العاصمة (الشمالية)',
    en: 'Capital School (Northern)',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة العاصمة (العاصمة)',
    en: 'Capital School (Capital)',
    kind: 'private',
    gov: 'capital',
  },
  {
    ar: 'مدرسة العروبة الابتدائية للبنات',
    en: 'Al Urooba Primary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة العلاء الحضرمي الابتدائية للبنين',
    en: 'Al Alaa Al Hadhrami Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة العهد الزاهر الثانوية للبنات',
    en: 'Al ʻAhad Al Zaher Secondary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الفاتح الثانوية للبنين',
    en: 'Al Fateh Secondary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الفارابي الابتدائية للبنين',
    en: 'Al Farabi Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة القادسية الابتدائية للبنات',
    en: 'Al Qadisiyah Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة القدس الابتدائية للبنات',
    en: 'Al Quds Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة القضيبية الابتدائية الاعدادية للبنين',
    en: 'Qudaybiyah Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة القلب المقدس (الجنوبية)',
    en: 'Sacred Heart School (Southern)',
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'مدرسة القلب المقدس (العاصمة)',
    en: 'Sacred Heart School (Capital)',
    kind: 'private',
    gov: 'capital',
  },
  {
    ar: 'مدرسة القيروان الاعدادية للبنات',
    en: 'Al Qayrawan Intermediate Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة المالكية الابتدائية الاعدادية للبنات',
    en: 'Al Malkiya Primary & Intermediate Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة المأمون الابتدائية للبنين',
    en: 'Al Mamoon Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة المتنبي الابتدائية للبينن',
    en: 'Almutanabi Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  { ar: 'مدرسة المجد الخاصة', en: 'Al Majd Private School', kind: 'private', gov: 'capital' },
  {
    ar: 'مدرسة المحرق الابتدائية للبنات',
    en: 'Al Muharraq Primary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة المحرق الثانوية للبنات',
    en: 'Al Muharraq Secondary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة المحرق الثانوية للبنين',
    en: 'Al Muharraq Secondary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة المدينة العالمية',
    en: 'City International School',
    kind: 'private',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة المستقبل الابتدائية للبنات',
    en: 'Al Mustaqbal Primary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  { ar: 'مدرسة المعارف الحديثة', en: 'Modern Knowledge Schools', kind: 'private', gov: 'capital' },
  {
    ar: 'مدرسة المعامير الابتدائية للبنين',
    en: 'Al MaʻAmeer Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة المعرفة الثانوية للبنات',
    en: 'Al Maarefa Female Secondary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  { ar: 'مدرسة المنار الخاصة', en: 'Al Manar Private Schools', kind: 'private', gov: 'northern' },
  {
    ar: 'مدرسة المنامة الثانوية للبنات',
    en: 'Manama Secondary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة المنذر بن ساوي التميمي الابتدائية للبنين',
    en: 'Al Munther Bin Sawi Altemeemy Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة المنهل الابتدائية للبنات',
    en: 'Al Manhal Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة المهد (الجنوبية)',
    en: 'Almahd Day Boarding School (Southern)',
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'مدرسة المهد (الشمالية)',
    en: 'Almahd School (Northern)',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة المهد (المحرق)',
    en: 'Almahd Day Boarding School (Muharraq)',
    kind: 'private',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الميثاق الوطني الاعدادية للبنين',
    en: 'National Charter Intermediate Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة النبيه صالح الابتدائية للبنات',
    en: 'Al Nabih Saleh Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  { ar: 'مدرسة النخيل الابتدائية', en: 'Palms Primary School', kind: 'private', gov: 'southern' },
  {
    ar: 'مدرسة النزهة الابتدائية للبنات',
    en: 'Al Nuzha Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة النسيم الدولية',
    en: 'Al Naseem Interntional School',
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'مدرسة النعيم الثانوية للبنين',
    en: 'Naim Secondary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة النور الثانوية للبنات',
    en: 'Al Noor Secondary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة النور العالمية (العاصمة 604)',
    en: 'Al Noor International School (Capital 604)',
    kind: 'private',
    gov: 'capital',
  },
  {
    ar: 'مدرسة النور العالمية (العاصمة 611)',
    en: 'Al Noor International School (Capital 611)',
    kind: 'private',
    gov: 'capital',
  },
  { ar: 'مدرسة النور الوطنية', en: 'Al Noor National School', kind: 'private', gov: 'muharraq' },
  {
    ar: 'مدرسة النويدرات الابتدائية للبنات',
    en: 'Nuwaidrat Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة الهداية الخليفية الثانوية للبنين',
    en: 'Al Hidayah Al Khalifa Secondary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة الوادي الابتدائية للبنين',
    en: 'Al Wadi Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة الوحدة الثانوية للبنين',
    en: 'Al Wehda Secondary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة الوفاء الثانوية للبنات',
    en: 'Al Wafa Secondary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة اليرموك الابتدائية للبنين',
    en: 'Al Yarmouk Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة أم الحصم الابتدائية للبنين',
    en: 'Umm Alhassam Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة أم القرى الابتدائية الاعدادية للبنات',
    en: 'Umm Al Qurra Primary Intermediate Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة أم أيمن الابتدائية للبنات',
    en: 'Umm Ayman Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة أم سلمة الاعدادية للبنات',
    en: 'Umm Salamah Intermediate Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة أم كلثوم الاعدادية للبنات',
    en: 'Umm Kalthoom Intermediate Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة أميمة بنت النعمان الثانوية للبنات',
    en: 'Omayma Bint Al Nuaman Secondary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة أوال الاعدادية للبنين',
    en: 'Awal Intermediate Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة اي ام اي الدولية',
    en: 'Ama International School',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة باربار الابتدائية للبنين',
    en: 'Bar Bar Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة بدر الكبرى الابتدائية للبنين',
    en: 'Bader Al Kubra Primary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة بريتوس الدولية',
    en: 'Britus International School',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة بلاد القديم الاعدادية للبينن',
    en: 'Bilad Alqadim Intermediate Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة بلقيس الابتدائية للبنات',
    en: 'Balqees Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة بوابة المعالي الخاصة',
    en: 'Bawabat Al MaaʻAli Private School',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة بوري الابتدائية للبنات',
    en: 'Buri Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة بوري الابتدائية للبنين',
    en: 'Buri Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة بيان البحرين النموذجية',
    en: 'Bahrain Bayan Model School',
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'مدرسة بيت الحكمة الابتدائية للبنات',
    en: 'Bait Al Hekma Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  { ar: 'مدرسة بيكن الخاصة', en: 'Beacon Private School', kind: 'private', gov: 'muharraq' },
  { ar: 'مدرسة تايلوس الخاصة', en: 'Taylos Private School', kind: 'private', gov: 'muharraq' },
  {
    ar: 'مدرسة توبلي الابتدائية للبنات',
    en: 'Tubli Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة توبلي الابتدائية للبنين',
    en: 'Tubli Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة جابر بن حيان الابتدائية للبنين',
    en: 'Jaber Bin Hayan Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة جدحفص الابتدائية للبنين',
    en: 'Jidhafs Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة جدحفص الاعدادية للبنين',
    en: 'Jidhafs Intermediate Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة جدحفص الثانوية الصناعية للبنين',
    en: 'Jidhafs Secondary Technical Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة جدحفص الثانوية للبنات',
    en: 'Jidhafs Secondary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة جو الابتدائية الاعدادية للبنات',
    en: 'Jaw Primary & Intermediate Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة حسان بن ثابت الابتدائية للبنين',
    en: 'Hasaan Bin Thabit Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة حطين الابتدائية للبنين',
    en: 'Hatteen Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة حفصة أم المؤمنين الابتدائية للبنات',
    en: 'Hafsa Umm Al Moaminin Primary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة حليمة السعدية الاعدادية للبنات',
    en: 'Halimah Al Saadiyah Intermediate Girls School',
    kind: 'public',
    gov: 'capital',
  },
  { ar: 'مدرسة حوار الدولية', en: 'Hawar International School', kind: 'private', gov: 'southern' },
  {
    ar: 'مدرسة خالد بن الوليد الابتدائية للبنين',
    en: 'Khalid Bin Al Waleed Primary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة خديجة الكبرى الاعدادية للبنات',
    en: 'Khadijah Al Kubra Intermediate Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة خولة الثانوية للبنات',
    en: 'Khawla Secondary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة ذا ون مالتي ناشونال',
    en: 'The One Multinational School',
    kind: 'private',
    gov: 'capital',
  },
  {
    ar: 'مدرسة رابعة العدوية الابتدائية للبنات',
    en: 'Rabeaa Aladawiya Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة رقية الابتدائية للبنات',
    en: 'Roquya Primary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة زبيدة الابتدائية للبنات',
    en: 'Zubaida Primary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة زنوبيا الاعدادية للبنات',
    en: 'Zanoobia Intermediate Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة زينب الاعدادية للبنات',
    en: 'Zainab Intermediate Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة سار الابتدائية للبنات',
    en: 'Sar Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة سار الابتدائية للبنين',
    en: 'Sar Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة سار الثانوية للبنات',
    en: 'Sar Secondary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة سافره الابتدائية الاعدادية للبنات',
    en: 'Safrah Primary & Intermediate Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة سافره الابتدائية الاعدادية للبنين',
    en: 'Safreh Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة سانت كريستوفر (الجنوبية)',
    en: "St. Christopher'S School (Southern)",
    kind: 'private',
    gov: 'southern',
  },
  {
    ar: 'مدرسة سانت كريستوفر (الشمالية)',
    en: "St. Christopher'S School (Northern)",
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة سبأ الابتدائية للبنات',
    en: 'Sabaa Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة سترة الابتدائية للبنات',
    en: 'Sitra Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة سترة الابتدائية للبنين',
    en: 'Sitra Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة سترة الاعدادية للبنات',
    en: 'Sitra Intermediate Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة سترة الثانوية للبنات',
    en: 'Sitra Secondary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة سعد بن أبي وقاص الابتدائية للبنين',
    en: 'Saad Bin Abi Waqas Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة سكينة بنت الحسين الابتدائية للبنات',
    en: 'Sakinah Bint Alhussain Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة سلماباد الابتدائية للبنات',
    en: 'Salimabad Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة سماهيج الابتدائية الاعدادية للبنين',
    en: 'Samaheej Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة سمو الشيخ محمد بن خليفة آل خليفة الابتدائية الاعدادية للبنين',
    en: 'Shaikh Muhammad Bin Khalifa Aal Khalifa Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة سمو الشيخة موزة بنت حمد آل خليفة الشاملة للبنات',
    en: 'Alshaikha Muza Bint Hamad Aal Khalifa Comprehensive Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة سمية الابتدائية للبنات',
    en: 'Sumayah Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة سند الابتدائية للبنات',
    en: 'Sanad Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة سند الابتدائية للبنين',
    en: 'Sanad Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة شهركان الابتدائية للبنات',
    en: 'Shahrakkan Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة صفية بنت عبدالمطلب الابتدائية للبنات',
    en: 'Safiya Bint Abdulmutalib Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة صلاح الدين الأيوبي الابتدائية للبنين',
    en: 'Salah Aldin Al Ayoubi Primary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة طارق بن زياد الاعدادية للبنين',
    en: 'Tariq Bin Ziyad Intermediate Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة طليطلة الابتدائية للبنات',
    en: 'Tulaitola Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة عائشة أم المؤمنين الابتدائية للبنات',
    en: 'ʻAisha Umm Al Moaminin Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة عالي الابتدائية للبنات',
    en: 'AʻAli Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة عالي الابتدائية للبنين',
    en: 'AʻAli Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة عالي الاعدادية للبنات',
    en: 'AʻAli Intermediate Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة عالي الاعدادية للبنين',
    en: 'AʻAli Intermediate Boys School',
    kind: 'public',
    gov: 'northern',
  },
  { ar: 'مدرسة عالية', en: 'Alia School', kind: 'private', gov: 'capital' },
  { ar: 'مدرسة عبد الرحمن كانو', en: 'Abdulrahman Kanoo School', kind: 'private', gov: 'muharraq' },
  {
    ar: 'مدرسة عبدالرحمن الداخل الاعدادية للبنين',
    en: 'Abdulrahman Aldakhil Intermediate Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة عبدالرحمن الناصر الابتدائية الاعدادية للبنين',
    en: 'Abdulrahman Al Nasser Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة عبدالرحمن كانو الدولية',
    en: 'Abdulrahman Kanoo International School',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة عثمان بن عفان الاعدادية للبنين',
    en: 'Othman Bin Affan Intermediate Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة عراد الابتدائية الاعدادية للبنين',
    en: 'Arad Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة عراد الابتدائية للبنات',
    en: 'Arad Primary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة عراد الابتدائية للبنين',
    en: 'Arad Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة عراد الاعدادية للبنات',
    en: 'Arad Intermediate Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة عسكر الابتدائية الاعدادية للبنين',
    en: 'Askar Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة عقبة بن نافع الابتدائية للبنين',
    en: 'Aqbah Bin Nafea Primary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة عمار بن ياسر الابتدائية للبنين',
    en: 'Ammar Ben Yaser Primary Boys School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة عمر بن الخطاب الابتدائية الاعدادية للبنين',
    en: 'Omar Bin Al Khattab Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة عمر بن عبدالعزيز الابتدائية للبنبن',
    en: 'Omar Bin Abdulaziz Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة عين جالوت الابتدائية للبنات',
    en: 'Ain Jaloot Primary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة غازي القصيبي الثانوية للبنات',
    en: 'Ghazi Al Gosaibi Secondary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة غرناطة الابتدائية للبنات',
    en: 'Gharnatah Primary Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة فاطمة الزهراء الابتدائية للبنات',
    en: "Fatimah Al Zahra' Primary Girls School",
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة فاطمة بنت أسد الابتدائية للبنات',
    en: 'Fatimah Bint Asad Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة فاطمة بنت الخطاب الابتدائية للبنات',
    en: 'Fatimah Bint Al Khattab Primary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة قرطبة الاعدادية للبنات',
    en: 'Kurtuba Intermediate Girls School',
    kind: 'public',
    gov: 'capital',
  },
  {
    ar: 'مدرسة قلالي الابتدائية للبنين',
    en: 'Qalali Primary Boys School',
    kind: 'public',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة كرانة الابتدائية للبنات',
    en: 'Karranah Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة كرزكان الابتدائية للبنين',
    en: 'Karzakkan Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة كواليتي ايديوكيشن',
    en: 'Quality Education School',
    kind: 'private',
    gov: 'northern',
  },
  {
    ar: 'مدرسة لؤلؤة الخليج العربي',
    en: 'Arabian Gulf Pearl School',
    kind: 'private',
    gov: 'capital',
  },
  {
    ar: 'مدرسة مدينة حمد الابتدائية للبنات',
    en: 'Hamad Town Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة مدينة حمد الابتدائية للبنين',
    en: 'Hamad Town Primary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة مدينة حمد الاعدادية للبنات',
    en: 'Hamad Town Intermediate Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة مدينة حمد الاعدادية للبنين',
    en: 'Hamad Town Intermediate Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة مدينة حمد الثانوية للبنات',
    en: 'Hamad Town Secondary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة مدينة حمد الثانوية للبنين',
    en: 'Hamad Town Secondary Boys School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة مدينة عيسى الابتدائية الاعدادية للبنين',
    en: 'Isa Town Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة مدينة عيسى الاعدادية للبنات',
    en: 'Isa Town Intermediate Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة مدينة عيسى الاعدادية للبنين',
    en: 'Isa Town Intermediate Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة مدينة عيسى الثانوية للبنات',
    en: 'Isa Town Secondary Girls School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة مدينة عيسى الثانوية للبنين',
    en: 'Isa Town Secondary Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة مريم بنت عمران الابتدائية للبنات',
    en: 'Mariam Bint Omran Primary Girls School',
    kind: 'public',
    gov: 'muharraq',
  },
  { ar: 'مدرسة نادين', en: 'Nadeen School', kind: 'private', gov: 'capital' },
  { ar: 'مدرسة نادين دلمونيا', en: 'Nadeen School Dilmunia', kind: 'private', gov: 'muharraq' },
  {
    ar: 'مدرسة نسيبة بنت كعب الابتدائية للبنات',
    en: 'Nusaiba Bint Kaab Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة نور الديار الخاصة',
    en: 'Noor Al Diyar Private School',
    kind: 'private',
    gov: 'muharraq',
  },
  {
    ar: 'مدرسة نيو جينيريشن انترناشيونال',
    en: 'New Generation International School',
    kind: 'private',
    gov: 'capital',
  },
  {
    ar: 'مدرسة هاجر الابتدائية للبنات',
    en: 'Hajar Primary Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'مدرسة وادي السيل الابتدائية الاعدادية للبنين',
    en: 'Wadi Alsail Primary & Intermediate Boys School',
    kind: 'public',
    gov: 'southern',
  },
  {
    ar: 'مدرسة يثرب الاعدادية للبنات',
    en: 'Yathreb Intermediate Girls School',
    kind: 'public',
    gov: 'northern',
  },
  {
    ar: 'معهد الشيخ خليفة للتكنولوجيا',
    en: 'Shaikh Khalifa Technology Institute',
    kind: 'public',
    gov: 'muharraq',
  },
];
