#!/usr/bin/env node
// Creates .env.production with fresh secrets and VAPID keys for infra/docker-compose.prod.yml.
//   node scripts/prod-env.mjs --domain app.example.com --mail-from "Wusool Safe <no-reply@example.com>"
// Never overwrites an existing file (rotating secrets would lock everyone out).
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import webpush from 'web-push';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const arg = (name, fallback) => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : fallback;
};
const out = path.join(root, arg('out', '.env.production'));
const domain = arg('domain');
if (!domain) {
  console.error(
    'usage: node scripts/prod-env.mjs --domain app.example.com [--mail-from "…"] [--out file]',
  );
  process.exit(2);
}
if (existsSync(out)) {
  console.error(`${out} already exists — refusing to overwrite secrets.`);
  process.exit(1);
}

const secret = (n = 48) => randomBytes(n).toString('base64url');
const vapid = webpush.generateVAPIDKeys();
const plainHttp = domain.startsWith(':');
const origin = plainHttp
  ? `http://localhost${domain === ':80' ? '' : domain}`
  : `https://${domain}`;

const env = `# Generated by scripts/prod-env.mjs on ${new Date().toISOString()}.
# Keep this file secret and backed up OUTSIDE the server (BACKUP_KEY decrypts the backups).

DOMAIN=${domain}
PUBLIC_API_URL=${origin}/v1
WEB_ORIGINS=${origin}

PG_PASSWORD=${secret(24)}
APP_DB_PASSWORD=${secret(24)}
SYSTEM_DB_PASSWORD=${secret(24)}

JWT_ACCESS_SECRET=${secret()}
JWT_REFRESH_SECRET=${secret()}
FIELD_ENCRYPTION_KEY=${randomBytes(32).toString('base64')}
PHOTO_URL_SECRET=${secret()}
BACKUP_KEY=${randomBytes(32).toString('base64')}
BACKUP_KEEP=14

VAPID_PUBLIC_KEY=${vapid.publicKey}
VAPID_PRIVATE_KEY=${vapid.privateKey}
VAPID_SUBJECT=mailto:${arg('vapid-email', `admin@${plainHttp ? 'example.com' : domain}`)}

# Email provider (Brevo, Resend, Amazon SES…), with SPF, DKIM and DMARC set for the domain.
SMTP_HOST=${arg('smtp-host', 'smtp.example.com')}
SMTP_PORT=${arg('smtp-port', '587')}
SMTP_SECURE=false
SMTP_USER=
SMTP_PASSWORD=
MAIL_FROM=${JSON.stringify(arg('mail-from', `Wusool Safe <no-reply@${plainHttp ? 'example.com' : domain}>`))}

# Optional error monitoring (off unless set).
SENTRY_DSN=

# Optional native app push (docs/RELEASE.md): Android via Firebase, iOS via APNs.
FCM_SERVICE_ACCOUNT_BASE64=
APNS_KEY_BASE64=
APNS_KEY_ID=
APNS_TEAM_ID=
APNS_BUNDLE_ID=com.wusoolsafe.app
APNS_ENV=production
`;
writeFileSync(out, env, { mode: 0o600 });
console.log(`✓ ${out} written. Fill in SMTP_* before going live.`);
