-- Kindergartens are their own kind of organisation, not a school.
ALTER TYPE "OrganizationType" ADD VALUE IF NOT EXISTS 'kindergarten';

-- Both names are required.
UPDATE "organizations" SET "name_en" = "name_ar" WHERE "name_en" IS NULL;
ALTER TABLE "organizations" ALTER COLUMN "name_en" SET NOT NULL;

-- No two schools, kindergartens or companies in one country may share a name: a guardian
-- picking their school must never see the same name twice. Independent drivers are found by
-- phone, not by name, and two of them may well be called the same — their key is their id.
ALTER TABLE "organizations"
  ADD COLUMN "name_key_ar" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "name_key_en" TEXT NOT NULL DEFAULT '';
UPDATE "organizations" SET
  "name_key_ar" = CASE WHEN "type" = 'independent_driver' THEN "id"::text ELSE lower("name_ar") END,
  "name_key_en" = CASE WHEN "type" = 'independent_driver' THEN "id"::text ELSE lower("name_en") END;
ALTER TABLE "organizations"
  ALTER COLUMN "name_key_ar" DROP DEFAULT,
  ALTER COLUMN "name_key_en" DROP DEFAULT;
CREATE UNIQUE INDEX "organizations_country_type_name_key_ar_key"
  ON "organizations" ("country", "type", "name_key_ar");
CREATE UNIQUE INDEX "organizations_country_type_name_key_en_key"
  ON "organizations" ("country", "type", "name_key_en");

-- Short code that tells two people with the same name apart. Drivers and schools search by it;
-- it is not a sign-in name. Generated by the database so every row always has one.
ALTER TABLE "students"
  ADD COLUMN "public_code" TEXT NOT NULL
  DEFAULT ('S' || upper(substr(md5((gen_random_uuid())::text), 1, 5)));
ALTER TABLE "users"
  ADD COLUMN "public_code" TEXT NOT NULL
  DEFAULT ('D' || upper(substr(md5((gen_random_uuid())::text), 1, 5)));
CREATE UNIQUE INDEX "students_public_code_key" ON "students" ("public_code");
CREATE UNIQUE INDEX "users_public_code_key" ON "users" ("public_code");
